//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Task_2_IMPLEMENTATION.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Task_2_IMPLEMENTATION.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream book_drop_sound {
            get {
                return ResourceManager.GetStream("book_drop_sound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bookcase_wallpaper {
            get {
                object obj = ResourceManager.GetObject("bookcase_wallpaper", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BookShelfBackGround {
            get {
                object obj = ResourceManager.GetObject("BookShelfBackGround", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream C418___Beginning_2__Minecraft_Volume_Beta_ {
            get {
                return ResourceManager.GetStream("C418___Beginning_2__Minecraft_Volume_Beta_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;class&quot;: &quot;C&quot;,
        ///    &quot;title&quot;: &quot;Auxiliary Sciences of History&quot;,
        ///    &quot;subclasses&quot;: [
        ///      {
        ///        &quot;code&quot;: &quot;CB&quot;,
        ///        &quot;title&quot;: &quot;History of Civilization&quot;,
        ///        &quot;entries&quot;: [
        ///          {&quot;callNumber&quot;: &quot;CB 3-482&quot;, &quot;description&quot;: &quot;History of Civilization&quot;},
        ///          {&quot;callNumber&quot;: &quot;CB 156&quot;, &quot;description&quot;: &quot;Terrestrial evidence of interplanetary voyages&quot;},
        ///          {&quot;callNumber&quot;: &quot;CB 158-161&quot;, &quot;description&quot;: &quot;Forecasts of future progress&quot;},
        ///          {&quot;callNumber&quot;: &quot;CB 195-281&quot;, &quot;descrip [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DeweyDecimalData {
            get {
                return ResourceManager.GetString("DeweyDecimalData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Dry_Hands {
            get {
                return ResourceManager.GetStream("Dry_Hands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Minecraft_Menu_Button_Sound_Effect___Sounffex {
            get {
                return ResourceManager.GetStream("Minecraft_Menu_Button_Sound_Effect___Sounffex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Wet_Hands {
            get {
                return ResourceManager.GetStream("Wet_Hands", resourceCulture);
            }
        }
    }
}
